### ISSUE TITLE
default search not working

### ISSUE THREAD

**Issue by kyeap** [Code-Operative/Reuse#104]
some user found out that when they search for sofa in the prestashop search it's not showing any results maybe the module is blocking the search from searching?

**Comment by elalelopez** [comment]
Fixed.

**Comment by elalelopez** [comment]
> some user found out that when they search for sofa in the prestashop search it's not showing any results maybe the module is blocking the search from searching?

Exactly. The native search is using the advancedsearch module, because we use hook product search provider, and this hook is a main hook from the core.

**Comment by kyeap** [comment]
> Fixed.

@elalelopez is the fix also in the dev server? I am still not able to search with the default search.

**Comment by elalelopez** [comment]
> > Fixed.
> 
> @elalelopez is the fix also in the dev server? I am still not able to search with the default search.

@kyeap , the fix is in the development1 branch
